In [29]:
import numpy as np

In [30]:
a1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a1)

a2 = np.arange(1, 10) ## 1에서부터 n-1까지의 범위를 생성. range()와 동일.
print(a2) # 1차원 배열만 생성한다.

## arange 함수와 비슷하게 1차원 배열을 생성. 단, 부동소수점을 포함한다.
## num 인수는 생성할 값의 수를 지정한다.
a3 = np.linspace(0, 1.0, num=5)
print(a3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[0.   0.25 0.5  0.75 1.  ]


In [31]:
empty_arr = np.empty(shape=(2, 2), dtype=np.int16, order="C")
## order는 행이나 열의 우선을 정한다. "C"는 행우선, "F"는 열우선

print(empty_arr)

[[    0     0]
 [    0 16368]]


In [32]:
a_eye = np.eye(4, dtype=np.int32)
print(f"np.eye() \n {a_eye} \n")

a_ones = np.ones((3, 3))
print(f"np.ones() \n {a_ones} \n")

a_zeros = np.zeros((3, 3))
print(f"np.zeros() \n {a_zeros} \n")

a_full = np.full((3, 3), fill_value=3.141592)
print(f"np.full() \n {a_full} \n")

np.eye() 
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]] 

np.ones() 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

np.zeros() 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

np.full() 
 [[3.141592 3.141592 3.141592]
 [3.141592 3.141592 3.141592]
 [3.141592 3.141592 3.141592]] 



In [33]:
## np.fromfunction은 shape인수로 전달된 값의 index를 인수로 사용하는 함수를 통해 배열을 생성하고 초기화한다.

def simple(n):
    return n + 1

a = np.fromfunction(simple, (5,)) ## shape = 5 ---> 0, 1, 2, 3, 4 가 simple function의 n으로 전달된다.
print(a)

[1. 2. 3. 4. 5.]


In [34]:
a = np.fromfunction(lambda r, c : r + c, (3, 3))
print(a)

[[0. 1. 2.]
 [1. 2. 3.]
 [2. 3. 4.]]


In [35]:
## numpy slicing
A = np.arange(1, 11)
print(A)

[ 1  2  3  4  5  6  7  8  9 10]


In [36]:
print(A[3:5]) ## slicing의 end는 end-1까지 값을 자른다.

[4 5]


In [37]:
## numpy의 slice의 흥미로운 점은 스칼라 값을 대입할 수 있다.
A[2:5] = 0
print(A)

A[2:5] += 100
print(A)

[ 1  2  0  0  0  6  7  8  9 10]
[  1   2 100 100 100   6   7   8   9  10]


In [38]:
A = np.arange(51)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50]


In [39]:
A[1] = 0
print(A)

A[2 * 2::2] = 0
print(A)

[ 0  0  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50]
[ 0  0  2  3  0  5  0  7  0  9  0 11  0 13  0 15  0 17  0 19  0 21  0 23
  0 25  0 27  0 29  0 31  0 33  0 35  0 37  0 39  0 41  0 43  0 45  0 47
  0 49  0]


In [40]:
A[3 * 3::3] = 0
print(A)

[ 0  0  2  3  0  5  0  7  0  0  0 11  0 13  0  0  0 17  0 19  0  0  0 23
  0 25  0  0  0 29  0 31  0  0  0 35  0 37  0  0  0 41  0 43  0  0  0 47
  0 49  0]


In [41]:
A[5 * 5::5] = 0
A[7 * 7::7] = 0

print(A)

[ 0  0  2  3  0  5  0  7  0  0  0 11  0 13  0  0  0 17  0 19  0  0  0 23
  0  0  0  0  0 29  0 31  0  0  0  0  0 37  0  0  0 41  0 43  0  0  0 47
  0  0  0]


In [42]:
P = A[A > 0] ## boolean array는 indexing 작업을 통해서만 배열 A자체에 마스크로 적용할 수 있다.
print(P)

[ 2  3  5  7 11 13 17 19 23 29 31 37 41 43 47]


In [43]:
A = np.arange(1, 17).reshape((4, 4))
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [44]:
print(A[1:3]) ## 1행부터 3-1행까지 가져온다.
print(A[:, 1:3]) ## 전체 행차원을 선택하고, 1열 ~ 3-1열까지 가져온다.

[[ 5  6  7  8]
 [ 9 10 11 12]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [45]:
a = np.arange(1, 10).reshape((3, 3))
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [46]:
print(a[0:1])

[[1 2 3]]


In [47]:
print(a[:, 0:1])

[[1]
 [4]
 [7]]


In [50]:
b = a > 4
print(b)

b = a * (a > 4)
print(b)

[[False False False]
 [False  True  True]
 [ True  True  True]]
[[0 0 0]
 [0 5 6]
 [7 8 9]]


In [51]:
A = np.random.randint(1, 20, (3, 4))
print(A)

[[13  5  4 16]
 [19  6  5 19]
 [ 2  7  8  2]]


In [53]:
print(np.sum(A, axis=0)) ## 열을 기준으로 총합.
print(np.sum(A, axis=1)) ## 행을 기준으로 총합.

[34 18 17 37]
[38 49 19]


In [56]:
a = np.array([[1, 2, 3, 4], 
              [5, 6, 7, 8], 
              [9, 10, 11, 12]])
print(a.shape) ## 3, 4

row_r1 = a[1, :]
print(row_r1)

row_r2 = a[2, :]
print(row_r2)


(3, 4)
[5 6 7 8]
[ 9 10 11 12]


In [57]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a[2, 1:4])

[8 9]


In [59]:
test_arr = np.arange(12).reshape((3, 4))
print(test_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [60]:
print(test_arr[0, :]) ## 0번째 행
print(test_arr[1, :]) ## 1번째 행

[0 1 2 3]
[4 5 6 7]


In [63]:
print(test_arr[1:3, 1:3])

[[ 5  6]
 [ 9 10]]


In [64]:
row_wise_sum = test_arr.sum(axis=0)
print(row_wise_sum)

[12 15 18 21]


In [65]:
col_wise_sum = test_arr.sum(axis=1)
print(col_wise_sum)

[ 6 22 38]
