In [1]:
import numpy as np

# numpy function

- array
- arange
- linspace
- fromfunction

## np.array
파이썬의 리스트나 튜플을 np.array()로 변환하는 방식으로 사용.  
인수들 중 order는 다차원 데이터가 어떻게 정렬되어야 할지 결정한다. 기본값은 K이며, 어떤 값을 설정하든 소스 데이터를 보존한다. C는 행 우선, F는 열 우선 순서를 따른다.

In [2]:
a1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## np.arange
1부터 N까지의 값으로 구성된 배열을 생성. 파이썬의 range함수와 유사하며, 1차원 배열만 생성할 수 있다.

In [3]:
a2 = np.arange(1, 10)
print(a2)

[1 2 3 4 5 6 7 8 9]


## np.linspace

np.arange 함수와 비슷하지만, 정수와 부동소수점도 함께다루며 항목간의 값 차이도 자유롭게 설정할 수 있다.  
arange함수처럼 1차원 배열만 생성한다.

In [4]:
a3 = np.linspace(0, 1.0, num=5) ## 0 ~ 1사이를 5개 값으로 분할
print(a3)

a4 = np.linspace(1., 10.0, num=8, endpoint=False) ## endpoint=False는 마지막 값을 포함시키지 않는다.
print(a4)

[0.   0.25 0.5  0.75 1.  ]
[1.    2.125 3.25  4.375 5.5   6.625 7.75  8.875]


## np.eye
numpy의 identity 함수와 비슷하며 2차원 배열만 생성한다. 행과 열의 번호가 동일한 원소는 1을 채우고 나머지는 0으로 채운다.

In [5]:
a_eye = np.eye(4, dtype=np.int32)
print(f"np.eye() \n {a_eye} \n")

a_eye = np.eye(N=4, M=5, dtype=np.int32)
print(f"np.eye() \n {a_eye} \n")

np.eye() 
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]] 

np.eye() 
 [[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]] 



## np.ones, np.zeros, np.full

np.ones, zeros, full 함수는 용도가 동일하다. 지정된 shape의 배열을 생성하되, ones는 1로, zeros는 0으로, full은 지정한 fill_value로 배열을 채운다.

In [6]:
a_ones = np.ones((3, 3))
print(f"np.ones() \n {a_ones} \n")

a_zeros = np.zeros((3, 3))
print(f"np.zeros() \n {a_zeros} \n")

a_full = np.full((3, 3), fill_value=3.141592)
print(f"np.full() \n {a_full} \n")

np.ones() 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

np.zeros() 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

np.full() 
 [[3.141592 3.141592 3.141592]
 [3.141592 3.141592 3.141592]
 [3.141592 3.141592 3.141592]] 



## np.fromfunction

np.fromfunction은 shape인수로 전달된 값의 index를 인수로 사용하는 함수를 통해 배열을 생성하고 초기화한다.


In [7]:
def simple(n):
    return n + 1

a = np.fromfunction(simple, (5,)) ## shape = 5 ---> 0, 1, 2, 3, 4 가 simple function의 n으로 전달된다.
print(a)

[1. 2. 3. 4. 5.]


In [8]:
## (0, 0), (0, 1), (0, 2)
## (1, 0), (1, 1), (1, 2)
## (2, 0), (2, 1), (2, 2)
a = np.fromfunction(lambda r, c : r + c, (3, 3))
print(a)

[[0. 1. 2.]
 [1. 2. 3.]
 [2. 3. 4.]]


In [9]:
def multiplication_table(target, num):
    return (target + 1) * (num + 1)

a = np.fromfunction(multiplication_table, (10, 10))
print(a)

str_a = str(a)
str_a = str_a.replace('[', '')
str_a = str_a.replace(']', '')
str_a = ' ' + str_a

print(str_a)

[[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [  2.   4.   6.   8.  10.  12.  14.  16.  18.  20.]
 [  3.   6.   9.  12.  15.  18.  21.  24.  27.  30.]
 [  4.   8.  12.  16.  20.  24.  28.  32.  36.  40.]
 [  5.  10.  15.  20.  25.  30.  35.  40.  45.  50.]
 [  6.  12.  18.  24.  30.  36.  42.  48.  54.  60.]
 [  7.  14.  21.  28.  35.  42.  49.  56.  63.  70.]
 [  8.  16.  24.  32.  40.  48.  56.  64.  72.  80.]
 [  9.  18.  27.  36.  45.  54.  63.  72.  81.  90.]
 [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]]
   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.
   2.   4.   6.   8.  10.  12.  14.  16.  18.  20.
   3.   6.   9.  12.  15.  18.  21.  24.  27.  30.
   4.   8.  12.  16.  20.  24.  28.  32.  36.  40.
   5.  10.  15.  20.  25.  30.  35.  40.  45.  50.
   6.  12.  18.  24.  30.  36.  42.  48.  54.  60.
   7.  14.  21.  28.  35.  42.  49.  56.  63.  70.
   8.  16.  24.  32.  40.  48.  56.  64.  72.  80.
   9.  18.  27.  36.  45.  54.  63.  72.  81.  90.
  10.  20.

# View

Slicing으로 만든 조각은 원본의 뷰(View)이다. 이는 원본 데이터의 복사본이 아니라는 뜻이다.  
따라서 뷰의 데이터를 변경하게 되면 원본 데이터도 함께 변경된다.

In [10]:
import numpy as np

arr1 = np.arange(7) # 0 1 2 3 4 5 6
arr1_slice = arr1[3:6] # 3 4 5
arr1_slice[0] = -1
print(f"arr1 : {arr1}")
print(f"arr1 slice : {arr1_slice}")

arr1 : [ 0  1  2 -1  4  5  6]
arr1 slice : [-1  4  5]


# Broad casting

numpy 배열을 만들면 스칼라 값과 결합하여 산술 연산을 할 수 있다.

In [11]:
a = np.arange(1, 10)
b = 2

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** b)

[ 3  4  5  6  7  8  9 10 11]
[-1  0  1  2  3  4  5  6  7]
[ 2  4  6  8 10 12 14 16 18]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[ 1  4  9 16 25 36 49 64 81]


배열 간 연산에서는 같은 구조(차원 수가 같고, 각차원의 크기가 같음)를 가져야 연산이 가능하다.

In [12]:
a = np.arange(1, 5).reshape(2, 2)
b = np.arange(6, 10).reshape(2, 2)

print(a.shape, b.shape)
print(a)
print(b)

(2, 2) (2, 2)
[[1 2]
 [3 4]]
[[6 7]
 [8 9]]


In [13]:
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** b)

[[ 7  9]
 [11 13]]
[[-5 -5]
 [-5 -5]]
[[ 6 14]
 [24 36]]
[[0.16666667 0.28571429]
 [0.375      0.44444444]]
[[     1    128]
 [  6561 262144]]


# Slicing

리스트 슬라이싱과 유사하다. 잘라낸 조각에 대입 연산자를 사용하면 메모리 속에 있는 값이 바로 변경된다.

In [16]:
a = np.arange(1, 10)
print(a)

slice1 = a[2:5]
slice1 += 100
print(a)
print(slice1)

[1 2 3 4 5 6 7 8 9]
[  1   2 103 104 105   6   7   8   9]
[103 104 105]


In [17]:
a = np.arange(1, 10)
print(a)

slice2 = a[2:5]
slice2 = slice2 + 100 ## 잘라낸 조각에 100을 더한 값을 재대입하는 것이므로 원래의 배열은 바뀌지 않는다.
print(a)
print(slice2)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[103 104 105]


# masking

- A > 0 : A의 각 항목 중 0보다 큰 값은 True, 작은 값은 False로 설정한 배열을 만든다.
- A[A > 5] : 5보다 큰 항목을 모두 선택한 배열을 만든다.
- A * (A > 5) : 원래의 배열 A와 boolean mask를 곱한 결과 배열 만든다.

In [22]:
b = np.arange(1, 10).reshape(3, 3)
b_mask1 = b > 5
print(b_mask1)

b_mask2 = b[b > 5]
print(b_mask2)

print(b)

[[False False False]
 [False False  True]
 [ True  True  True]]
[6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
a = np.arange(1, 10).reshape(3, 3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
axis_0 = np.sum(a, axis=0)
print(axis_0)

[12 15 18]
